//! Architecture-specific syscall number → name tables.
//!
//! Curated to the syscalls that matter for diagnosing send/recv freezes —
//! network I/O, polling, scheduling, futex, fs I/O.

#[cfg(target_arch = "x86_64")]
pub fn name(nr: u64) -> &'static str {
    match nr {
        0 => "read",
        1 => "write",
        2 => "open",
        3 => "close",
        4 => "stat",
        5 => "fstat",
        7 => "poll",
        8 => "lseek",
        9 => "mmap",
        17 => "pread64",
        18 => "pwrite64",
        19 => "readv",
        20 => "writev",
        22 => "pipe",
        23 => "select",
        24 => "sched_yield",
        32 => "dup",
        33 => "dup2",
        34 => "pause",
        35 => "nanosleep",
        41 => "socket",
        42 => "connect",
        43 => "accept",
        44 => "sendto",
        45 => "recvfrom",
        46 => "sendmsg",
        47 => "recvmsg",
        48 => "shutdown",
        49 => "bind",
        50 => "listen",
        51 => "getsockname",
        52 => "getpeername",
        53 => "socketpair",
        54 => "setsockopt",
        55 => "getsockopt",
        56 => "clone",
        60 => "exit",
        61 => "wait4",
        62 => "kill",
        72 => "fcntl",
        73 => "flock",
        85 => "creat",
        87 => "unlink",
        202 => "futex",
        228 => "clock_gettime",
        230 => "clock_nanosleep",
        232 => "epoll_wait",
        233 => "epoll_ctl",
        247 => "waitid",
        270 => "pselect6",
        271 => "ppoll",
        281 => "epoll_pwait",
        288 => "accept4",
        318 => "getrandom",
        425 => "io_uring_setup",
        426 => "io_uring_enter",
        427 => "io_uring_register",
        441 => "epoll_pwait2",
        _ => "syscall",
    }
}

#[cfg(target_arch = "aarch64")]
pub fn name(nr: u64) -> &'static str {
    // aarch64 generic syscall numbers (asm-generic/unistd.h)
    match nr {
        17 => "getcwd",
        19 => "epoll_ctl",
        20 => "epoll_pwait",
        22 => "close",
        23 => "dup",
        25 => "fcntl",
        46 => "ftruncate",
        56 => "openat",
        57 => "close",
        59 => "pipe2",
        61 => "getdents64",
        62 => "lseek",
        63 => "read",
        64 => "write",
        65 => "readv",
        66 => "writev",
        67 => "pread64",
        68 => "pwrite64",
        71 => "sendfile",
        72 => "pselect6",
        73 => "ppoll",
        78 => "readlinkat",
        79 => "fstatat",
        80 => "fstat",
        93 => "exit",
        94 => "exit_group",
        95 => "waitid",
        96 => "set_tid_address",
        98 => "futex",
        101 => "nanosleep",
        113 => "clock_gettime",
        115 => "clock_nanosleep",
        124 => "sched_yield",
        198 => "socket",
        199 => "socketpair",
        200 => "bind",
        201 => "listen",
        202 => "accept",
        203 => "connect",
        204 => "getsockname",
        205 => "getpeername",
        206 => "sendto",
        207 => "recvfrom",
        208 => "setsockopt",
        209 => "getsockopt",
        210 => "shutdown",
        211 => "sendmsg",
        212 => "recvmsg",
        220 => "clone",
        221 => "execve",
        222 => "mmap",
        242 => "accept4",
        278 => "getrandom",
        425 => "io_uring_setup",
        426 => "io_uring_enter",
        427 => "io_uring_register",
        441 => "epoll_pwait2",
        _ => "syscall",
    }
}

#[cfg(not(any(target_arch = "x86_64", target_arch = "aarch64")))]
pub fn name(_nr: u64) -> &'static str {
    "syscall"
}
